/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulp.Vistas;


import javax.swing.JOptionPane;
import ulp.ImagenFondo;

/**
 *
 * @author Cristian
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        Escritorio.setBorder(new ImagenFondo());
        this.setExtendedState(Principal.NORMAL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        Escritorio = new javax.swing.JDesktopPane();
        btnAlumnos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuFormAlumno = new javax.swing.JMenuItem();
        menuFormMateria = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuFormInscripciones = new javax.swing.JMenuItem();
        menuManipulacionNotas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuAlumnosXmaterias = new javax.swing.JMenuItem();
        MenuTodasLasMaterias = new javax.swing.JMenuItem();
        MenuAlumnos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAlumnos.setBackground(new java.awt.Color(102, 102, 102));
        btnAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/alumno.jpg"))); // NOI18N
        btnAlumnos.setText("Alumnos");
        btnAlumnos.setOpaque(true);
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosActionPerformed(evt);
            }
        });

        Escritorio.setLayer(btnAlumnos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAlumnos)
                .addContainerGap(862, Short.MAX_VALUE))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAlumnos)
                .addContainerGap(509, Short.MAX_VALUE))
        );

        jMenu1.setText("Alumno");

        menuFormAlumno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuFormAlumno.setText("Formulario de Alumno");
        menuFormAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFormAlumnoActionPerformed(evt);
            }
        });
        jMenu1.add(menuFormAlumno);

        jMenuBar1.add(jMenu1);

        menuFormMateria.setText("Materia");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Formulario de Materia");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuFormMateria.add(jMenuItem3);

        jMenuBar1.add(menuFormMateria);

        jMenu3.setText("Administracion");

        menuFormInscripciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menuFormInscripciones.setText("Manejo de Inscripciones");
        menuFormInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFormInscripcionesActionPerformed(evt);
            }
        });
        jMenu3.add(menuFormInscripciones);

        menuManipulacionNotas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuManipulacionNotas.setText("Manipulacion de notas");
        menuManipulacionNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManipulacionNotasActionPerformed(evt);
            }
        });
        jMenu3.add(menuManipulacionNotas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");

        MenuAlumnosXmaterias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        MenuAlumnosXmaterias.setText("Alumnos por materia");
        MenuAlumnosXmaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAlumnosXmateriasActionPerformed(evt);
            }
        });
        jMenu4.add(MenuAlumnosXmaterias);

        MenuTodasLasMaterias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        MenuTodasLasMaterias.setText("Todas Las Materias");
        MenuTodasLasMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTodasLasMateriasActionPerformed(evt);
            }
        });
        jMenu4.add(MenuTodasLasMaterias);

        MenuAlumnos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        MenuAlumnos.setText("Todos Los Alumnos");
        MenuAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAlumnosActionPerformed(evt);
            }
        });
        jMenu4.add(MenuAlumnos);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Salir");

        menuSalir.setText("salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu5.add(menuSalir);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        FormularioMateria mate = new FormularioMateria();
        Escritorio.add(mate);
        mate.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuManipulacionNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManipulacionNotasActionPerformed
        FormularioNotas nota = new FormularioNotas();
        Escritorio.add(nota);
        nota.show();

    }//GEN-LAST:event_menuManipulacionNotasActionPerformed

    private void menuFormAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFormAlumnoActionPerformed
        //Instancio una ventana del menú formulario alumno para q me muestre la ventana de gestion de alumno
//        GestionAlumno alu = new GestionAlumno();
        FormularioAlumno alu = new FormularioAlumno();
        //la hago visible y la posiciono en el centro
        Escritorio.add(alu);
        alu.show();


    }//GEN-LAST:event_menuFormAlumnoActionPerformed

    private void menuFormInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFormInscripcionesActionPerformed
        FormularioDeInscripcion insc = new FormularioDeInscripcion();
        Escritorio.add(insc);
        insc.show();
    }//GEN-LAST:event_menuFormInscripcionesActionPerformed

    private void MenuAlumnosXmateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAlumnosXmateriasActionPerformed
        FormularioConsulta c = new FormularioConsulta();
        Escritorio.add(c);
        c.show();
    }//GEN-LAST:event_MenuAlumnosXmateriasActionPerformed

    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed
        RegistroAlumnos r = new RegistroAlumnos();
        Escritorio.add(r);
        r.show();
    }//GEN-LAST:event_btnAlumnosActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de que quieres cerrar la aplicación?",
                "Confirmar Cierre",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION){
            
            System.exit(0);
        }
    }//GEN-LAST:event_menuSalirActionPerformed

    private void MenuTodasLasMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTodasLasMateriasActionPerformed
    
        TodasMaterias tm = new TodasMaterias();
        Escritorio.add(tm);
        tm.show();
        tm.setLocation(100,0);
        
    }//GEN-LAST:event_MenuTodasLasMateriasActionPerformed

    private void MenuAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAlumnosActionPerformed
        TdosAlumnos al = new TdosAlumnos();
        Escritorio.add(al);
        al.show();
        al.setLocation(150, 0);
    }//GEN-LAST:event_MenuAlumnosActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Principal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem MenuAlumnos;
    private javax.swing.JMenuItem MenuAlumnosXmaterias;
    private javax.swing.JMenuItem MenuTodasLasMaterias;
    private javax.swing.JButton btnAlumnos;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem menuFormAlumno;
    private javax.swing.JMenuItem menuFormInscripciones;
    private javax.swing.JMenu menuFormMateria;
    private javax.swing.JMenuItem menuManipulacionNotas;
    private javax.swing.JMenuItem menuSalir;
    // End of variables declaration//GEN-END:variables
}
